test:
	go test -v -coverprofile=coverage.out --cover . ./extensions/...
	go vet . ./extensions/...
	golint . ./extensions/...
	golangci-lint run . ./extensions/...
	go tool cover --func=coverage.out

bench:
	go test -v --benchmem --bench=. . ./extensions/...
